/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PaymentMethod 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4989175559215430166L;
    private String username;
    private String description;
    private InputStream isActive;
    /** GETTER
     * The username
     */
    @JsonGetter("username")
    public String getUsername ( ) { 
        return this.username;
    }
    
    /** SETTER
     * The username
     */
    @JsonSetter("username")
    public void setUsername (String value) { 
        this.username = value;
        notifyObservers(this.username);
    }
 
    /** GETTER
     * The description
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * The description
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
        notifyObservers(this.description);
    }
 
    /** GETTER
     * Is the payment method active? (true, false)
     */
    @JsonGetter("is_active")
    public InputStream getIsActive ( ) { 
        return this.isActive;
    }
    
    /** SETTER
     * Is the payment method active? (true, false)
     */
    @JsonSetter("is_active")
    public void setIsActive (InputStream value) { 
        this.isActive = value;
        notifyObservers(this.isActive);
    }
 
}
 