/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RedemptionRequestForm 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4710067144678116677L;
    private RedemptionRequest redemptionRequest;
    /** GETTER
     * The redemption request's wrapper
     */
    @JsonGetter("redemption_request")
    public RedemptionRequest getRedemptionRequest ( ) { 
        return this.redemptionRequest;
    }
    
    /** SETTER
     * The redemption request's wrapper
     */
    @JsonSetter("redemption_request")
    public void setRedemptionRequest (RedemptionRequest value) { 
        this.redemptionRequest = value;
        notifyObservers(this.redemptionRequest);
    }
 
}
 