/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api;

import android.content.Context;
import com.android.volley.RequestQueue;
import com.android.volley.toolbox.Volley;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://api.geniusreferrals.com";


    //retains status whether we have already initialized
    private static boolean initialized = false;
    private static RequestQueue requestQueue = null;

    //Initialization of configuration
    public static void initialize(Context context){
        requestQueue = Volley.newRequestQueue(context);
    
        initialized = true;
    }

    // volley request queue needs to be initialized before use
    public static RequestQueue getRequestQueue() {
        if(!initialized)
            throw new IllegalStateException("Must initialize before accessing request queue");
        return requestQueue;
    }

    //The content type
    //TODO: Replace the contentType with an appropriate value
    public static String contentType = "application/json";

    //Your API Token, you can get your token here https://www.geniusreferrals.com/en/settings/api-access
    //TODO: Replace the xAuthToken with an appropriate value
    public static String xAuthToken = "3b9d11374b602fb47b987dff90f1c5940a1f377f";

}
